const japaneseVocabulary = [
  {
    id: "word001",
    word: "こんにちは",
    pronunciation: "konnichiwa",
    meaning: "hello",
    part_of_speech: "expression",
    difficulty: "easy",
    lesson_no: 1,
    when_to_say: "Used as a greeting during the day.",
    example: "こんにちは、元気ですか？ (konnichiwa, genki desu ka?) - Hello, how are you?"
  },
  {
    id: "word002",
    word: "ありがとう",
    pronunciation: "arigatou",
    meaning: "thank you",
    part_of_speech: "expression",
    difficulty: "easy",
    lesson_no: 1,
    when_to_say: "Used to express gratitude in informal settings.",
    example: "ありがとう、手伝ってくれて！ (arigatou, tetsudatte kurete!) - Thank you for helping me!"
  },
  {
    id: "word003",
    word: "さようなら",
    pronunciation: "sayounara",
    meaning: "goodbye",
    part_of_speech: "expression",
    difficulty: "easy",
    lesson_no: 1,
    when_to_say: "Used when parting for a longer time or formally.",
    example: "さようなら、また会いましょう。 (sayounara, mata aimashou.) - Goodbye, let's meet again."
  },
  {
    id: "word004",
    word: "おはよう",
    pronunciation: "ohayou",
    meaning: "good morning",
    part_of_speech: "expression",
    difficulty: "easy",
    lesson_no: 1,
    when_to_say: "Used as a morning greeting in casual settings.",
    example: "おはよう、よく寝た？ (ohayou, yoku neta?) - Good morning, did you sleep well?"
  },
  {
    id: "word005",
    word: "こんばんは",
    pronunciation: "konbanwa",
    meaning: "good evening",
    part_of_speech: "expression",
    difficulty: "easy",
    lesson_no: 1,
    when_to_say: "Used as an evening greeting.",
    example: "こんばんは、素敵な夜ですね。 (konbanwa, suteki na yoru desu ne.) - Good evening, it's a nice night, isn't it?"
  },
  {
    id: "word006",
    word: "はい",
    pronunciation: "hai",
    meaning: "yes",
    part_of_speech: "adverb",
    difficulty: "easy",
    lesson_no: 1,
    when_to_say: "Used to affirm or agree.",
    example: "はい、それは正しいです。 (hai, sore wa tadashii desu.) - Yes, that is correct."
  },
  {
    id: "word007",
    word: "いいえ",
    pronunciation: "iie",
    meaning: "no",
    part_of_speech: "adverb",
    difficulty: "easy",
    lesson_no: 1,
    when_to_say: "Used to deny or disagree.",
    example: "いいえ、私は日本人ではありません。 (iie, watashi wa nihonjin dewa arimasen.) - No, I am not Japanese."
  },
  {
    id: "word008",
    word: "お願いします",
    pronunciation: "onegaishimasu",
    meaning: "please",
    part_of_speech: "expression",
    difficulty: "easy",
    lesson_no: 1,
    when_to_say: "Used when making a request.",
    example: "水をください、お願いします。 (mizu wo kudasai, onegaishimasu.) - Water please."
  },
  {
    id: "word009",
    word: "すみません",
    pronunciation: "sumimasen",
    meaning: "excuse me/sorry",
    part_of_speech: "expression",
    difficulty: "easy",
    lesson_no: 1,
    when_to_say: "Used to apologize or get someone's attention.",
    example: "すみません、トイレはどこですか？ (sumimasen, toire wa doko desu ka?) - Excuse me, where is the toilet?"
  },
  {
    id: "word010",
    word: "分かりました",
    pronunciation: "wakarimashita",
    meaning: "I understand",
    part_of_speech: "expression",
    difficulty: "easy",
    lesson_no: 1,
    when_to_say: "Used to indicate understanding or acknowledgment.",
    example: "はい、分かりました。明日やります。 (hai, wakarimashita. ashita yarimasu.) - Yes, I understand. I'll do it tomorrow."
  },
  {
    id: "word011",
    word: "水",
    pronunciation: "mizu",
    meaning: "water",
    part_of_speech: "noun",
    difficulty: "easy",
    lesson_no: 2,
    when_to_say: "When referring to water.",
    example: "水を飲みたいです。 (mizu wo nomitai desu.) - I want to drink water."
  },
  {
    id: "word012",
    word: "食べる",
    pronunciation: "taberu",
    meaning: "to eat",
    part_of_speech: "verb",
    difficulty: "easy",
    lesson_no: 2,
    when_to_say: "When talking about eating.",
    example: "私は寿司を食べます。 (watashi wa sushi wo tabemasu.) - I eat sushi."
  },
  {
    id: "word013",
    word: "飲む",
    pronunciation: "nomu",
    meaning: "to drink",
    part_of_speech: "verb",
    difficulty: "easy",
    lesson_no: 2,
    when_to_say: "When talking about drinking.",
    example: "彼はコーヒーを飲みます。 (kare wa koohii wo nomimasu.) - He drinks coffee."
  },
  {
    id: "word014",
    word: "行く",
    pronunciation: "iku",
    meaning: "to go",
    part_of_speech: "verb",
    difficulty: "easy",
    lesson_no: 2,
    when_to_say: "When talking about going somewhere.",
    example: "明日、学校に行きます。 (ashita, gakkou ni ikimasu.) - I will go to school tomorrow."
  },
  {
    id: "word015",
    word: "見る",
    pronunciation: "miru",
    meaning: "to see/to watch",
    part_of_speech: "verb",
    difficulty: "easy",
    lesson_no: 2,
    when_to_say: "When talking about seeing or watching something.",
    example: "映画を見ました。 (eiga wo mimashita.) - I watched a movie."
  },
  {
    id: "word016",
    word: "聞く",
    pronunciation: "kiku",
    meaning: "to listen/to hear",
    part_of_speech: "verb",
    difficulty: "easy",
    lesson_no: 2,
    when_to_say: "When talking about listening or hearing.",
    example: "音楽を聞いています。 (ongaku wo kiite imasu.) - I am listening to music."
  },
  {
    id: "word017",
    word: "読む",
    pronunciation: "yomu",
    meaning: "to read",
    part_of_speech: "verb",
    difficulty: "easy",
    lesson_no: 2,
    when_to_say: "When talking about reading.",
    example: "私は本を読みます。 (watashi wa hon wo yomimasu.) - I read books."
  },
  {
    id: "word018",
    word: "書く",
    pronunciation: "kaku",
    meaning: "to write",
    part_of_speech: "verb",
    difficulty: "easy",
    lesson_no: 2,
    when_to_say: "When talking about writing.",
    example: "手紙を書きました。 (tegami wo kakimashita.) - I wrote a letter."
  },
  {
    id: "word019",
    word: "話す",
    pronunciation: "hanasu",
    meaning: "to speak/to talk",
    part_of_speech: "verb",
    difficulty: "easy",
    lesson_no: 2,
    when_to_say: "When talking about speaking or conversing.",
    example: "彼は日本語を話します。 (kare wa nihongo wo hanashimasu.) - He speaks Japanese."
  },
  {
    id: "word020",
    word: "買う",
    pronunciation: "kau",
    meaning: "to buy",
    part_of_speech: "verb",
    difficulty: "easy",
    lesson_no: 2,
    when_to_say: "When talking about purchasing something.",
    example: "新しい服を買いました。 (atarashii fuku wo kaimashita.) - I bought new clothes."
  },
  {
    id: "word021",
    word: "一",
    pronunciation: "ichi",
    meaning: "one",
    part_of_speech: "numeral",
    difficulty: "easy",
    lesson_no: 3,
    when_to_say: "When counting or referring to the number one.",
    example: "一人の男の子 (hitori no otoko no ko) - One boy"
  },
  {
    id: "word022",
    word: "二",
    pronunciation: "ni",
    meaning: "two",
    part_of_speech: "numeral",
    difficulty: "easy",
    lesson_no: 3,
    when_to_say: "When counting or referring to the number two.",
    example: "二冊の本 (nisatsu no hon) - Two books"
  },
  {
    id: "word023",
    word: "三",
    pronunciation: "san",
    meaning: "three",
    part_of_speech: "numeral",
    difficulty: "easy",
    lesson_no: 3,
    when_to_say: "When counting or referring to the number three.",
    example: "三枚の写真 (sanmai no shashin) - Three photos"
  },
  {
    id: "word024",
    word: "四",
    pronunciation: "yon/shi",
    meaning: "four",
    part_of_speech: "numeral",
    difficulty: "easy",
    lesson_no: 3,
    when_to_say: "When counting or referring to the number four.",
    example: "四つの箱 (yottsu no hako) - Four boxes"
  },
  {
    id: "word025",
    word: "五",
    pronunciation: "go",
    meaning: "five",
    part_of_speech: "numeral",
    difficulty: "easy",
    lesson_no: 3,
    when_to_say: "When counting or referring to the number five.",
    example: "五歳の子供 (gosai no kodomo) - Five-year-old child"
  },
  {
    id: "word026",
    word: "家族",
    pronunciation: "kazoku",
    meaning: "family",
    part_of_speech: "noun",
    difficulty: "medium",
    lesson_no: 4,
    when_to_say: "When talking about family or relatives.",
    example: "私の家族は五人です。 (watashi no kazoku wa gonin desu.) - My family has five people."
  },
  {
    id: "word027",
    word: "母",
    pronunciation: "haha",
    meaning: "mother",
    part_of_speech: "noun",
    difficulty: "medium",
    lesson_no: 4,
    when_to_say: "When referring to one's own mother.",
    example: "母は先生です。 (haha wa sensei desu.) - My mother is a teacher."
  },
  {
    id: "word028",
    word: "父",
    pronunciation: "chichi",
    meaning: "father",
    part_of_speech: "noun",
    difficulty: "medium",
    lesson_no: 4,
    when_to_say: "When referring to one's own father.",
    example: "父は会社員です。 (chichi wa kaishain desu.) - My father is a company employee."
  },
  {
    id: "word029",
    word: "兄",
    pronunciation: "ani",
    meaning: "older brother",
    part_of_speech: "noun",
    difficulty: "medium",
    lesson_no: 4,
    when_to_say: "When referring to one's own older brother.",
    example: "兄は大学生です。 (ani wa daigakusei desu.) - My older brother is a university student."
  },
  {
    id: "word030",
    word: "姉",
    pronunciation: "ane",
    meaning: "older sister",
    part_of_speech: "noun",
    difficulty: "medium",
    lesson_no: 4,
    when_to_say: "When referring to one's own older sister.",
    example: "姉は医者です。 (ane wa isha desu.) - My older sister is a doctor."
  },
  {
    id: "word031",
    word: "天気",
    pronunciation: "tenki",
    meaning: "weather",
    part_of_speech: "noun",
    difficulty: "medium",
    lesson_no: 5,
    when_to_say: "When talking about the weather.",
    example: "今日の天気はいいですね。 (kyou no tenki wa ii desu ne.) - Today's weather is nice, isn't it?"
  },
  {
    id: "word032",
    word: "雨",
    pronunciation: "ame",
    meaning: "rain",
    part_of_speech: "noun",
    difficulty: "medium",
    lesson_no: 5,
    when_to_say: "When talking about rain.",
    example: "雨が降っています。 (ame ga futte imasu.) - It's raining."
  },
  {
    id: "word033",
    word: "雪",
    pronunciation: "yuki",
    meaning: "snow",
    part_of_speech: "noun",
    difficulty: "medium",
    lesson_no: 5,
    when_to_say: "When talking about snow.",
    example: "雪が降っています。 (yuki ga futte imasu.) - It's snowing."
  },
  {
    id: "word034",
    word: "曇り",
    pronunciation: "kumori",
    meaning: "cloudy",
    part_of_speech: "noun",
    difficulty: "medium",
    lesson_no: 5,
    when_to_say: "When describing cloudy weather.",
    example: "今日は曇りです。 (kyou wa kumori desu.) - Today is cloudy."
  },
  {
    id: "word035",
    word: "晴れ",
    pronunciation: "hare",
    meaning: "sunny",
    part_of_speech: "noun",
    difficulty: "medium",
    lesson_no: 5,
    when_to_say: "When describing sunny weather.",
    example: "明日は晴れでしょう。 (ashita wa hare deshou.) - Tomorrow will be sunny."
  },
  {
    id: "word036",
    word: "学校",
    pronunciation: "gakkou",
    meaning: "school",
    part_of_speech: "noun",
    difficulty: "medium",
    lesson_no: 6,
    when_to_say: "When talking about school.",
    example: "私は学校に行きます。 (watashi wa gakkou ni ikimasu.) - I go to school."
  },
  {
    id: "word037",
    word: "先生",
    pronunciation: "sensei",
    meaning: "teacher",
    part_of_speech: "noun",
    difficulty: "medium",
    lesson_no: 6,
    when_to_say: "When referring to a teacher or instructor.",
    example: "先生はとても親切です。 (sensei wa totemo shinsetsu desu.) - The teacher is very kind."
  },
  {
    id: "word038",
    word: "学生",
    pronunciation: "gakusei",
    meaning: "student",
    part_of_speech: "noun",
    difficulty: "medium",
    lesson_no: 6,
    when_to_say: "When referring to a student.",
    example: "私は大学の学生です。 (watashi wa daigaku no gakusei desu.) - I am a university student."
  },
  {
    id: "word039",
    word: "教室",
    pronunciation: "kyoushitsu",
    meaning: "classroom",
    part_of_speech: "noun",
    difficulty: "medium",
    lesson_no: 6,
    when_to_say: "When referring to a classroom.",
    example: "教室は2階にあります。 (kyoushitsu wa nikai ni arimasu.) - The classroom is on the second floor."
  },
  {
    id: "word040",
    word: "授業",
    pronunciation: "jugyou",
    meaning: "class/lesson",
    part_of_speech: "noun",
    difficulty: "medium",
    lesson_no: 6,
    when_to_say: "When talking about a class or lesson.",
    example: "授業は9時に始まります。 (jugyou wa kuji ni hajimarimasu.) - The class starts at 9 o'clock."
  },
  {
    id: "word041",
    word: "愛してる",
    pronunciation: "aishiteru",
    meaning: "I love you",
    part_of_speech: "expression",
    difficulty: "difficult",
    lesson_no: 7,
    when_to_say: "Rarely used directly in Japanese culture; reserved for serious romantic relationships.",
    example: "愛してるよ、ずっと一緒にいたい。 (aishiteru yo, zutto issho ni itai.) - I love you, I want to be together forever."
  },
  {
    id: "word042",
    word: "頑張って",
    pronunciation: "ganbatte",
    meaning: "do your best",
    part_of_speech: "expression",
    difficulty: "medium",
    lesson_no: 7,
    when_to_say: "Used to encourage someone to do their best or to persevere.",
    example: "試験頑張って！ (shiken ganbatte!) - Do your best on the exam!"
  },
  {
    id: "word043",
    word: "お疲れ様",
    pronunciation: "otsukaresama",
    meaning: "good work/thank you for your hard work",
    part_of_speech: "expression",
    difficulty: "difficult",
    lesson_no: 7,
    when_to_say: "Used to acknowledge someone's effort or hard work, especially at the end of work or an activity.",
    example: "今日も一日お疲れ様でした。 (kyou mo ichinichi otsukaresama deshita.) - Thank you for your hard work today as well."
  },
  {
    id: "word044",
    word: "いただきます",
    pronunciation: "itadakimasu",
    meaning: "let's eat/I gratefully receive",
    part_of_speech: "expression",
    difficulty: "medium",
    lesson_no: 7,
    when_to_say: "Said before starting to eat a meal, expressing gratitude for the food.",
    example: "いただきます。 (itadakimasu.) - Let's eat."
  },
  {
    id: "word045",
    word: "ごちそうさま",
    pronunciation: "gochisousama",
    meaning: "thank you for the meal",
    part_of_speech: "expression",
    difficulty: "medium",
    lesson_no: 7,
    when_to_say: "Said after finishing a meal, expressing gratitude for the food.",
    example: "ごちそうさまでした。 (gochisousama deshita.) - Thank you for the meal."
  },
  {
    id: "word046",
    word: "季節",
    pronunciation: "kisetsu",
    meaning: "season",
    part_of_speech: "noun",
    difficulty: "difficult",
    lesson_no: 8,
    when_to_say: "When talking about seasons.",
    example: "日本には四つの季節があります。 (nihon ni wa yottsu no kisetsu ga arimasu.) - Japan has four seasons."
  },
  {
    id: "word047",
    word: "春",
    pronunciation: "haru",
    meaning: "spring",
    part_of_speech: "noun",
    difficulty: "medium",
    lesson_no: 8,
    when_to_say: "When talking about the spring season.",
    example: "春は桜の季節です。 (haru wa sakura no kisetsu desu.) - Spring is the season of cherry blossoms."
  },
  {
    id: "word048",
    word: "夏",
    pronunciation: "natsu",
    meaning: "summer",
    part_of_speech: "noun",
    difficulty: "medium",
    lesson_no: 8,
    when_to_say: "When talking about the summer season.",
    example: "夏は暑いです。 (natsu wa atsui desu.) - Summer is hot."
  },
  {
    id: "word049",
    word: "秋",
    pronunciation: "aki",
    meaning: "autumn/fall",
    part_of_speech: "noun",
    difficulty: "medium",
    lesson_no: 8,
    when_to_say: "When talking about the autumn/fall season.",
    example: "秋は紅葉がきれいです。 (aki wa kouyou ga kirei desu.) - The autumn leaves are beautiful in fall."
  },
  {
    id: "word050",
    word: "冬",
    pronunciation: "fuyu",
    meaning: "winter",
    part_of_speech: "noun",
    difficulty: "medium",
    lesson_no: 8,
    when_to_say: "When talking about the winter season.",
    example: "冬は寒いです。 (fuyu wa samui desu.) - Winter is cold."
  },
  {
    id: "word051",
    word: "料理",
    pronunciation: "ryouri",
    meaning: "cooking/cuisine",
    part_of_speech: "noun",
    difficulty: "difficult",
    lesson_no: 9,
    when_to_say: "When talking about cooking or cuisine.",
    example: "日本料理が好きです。 (nihon ryouri ga suki desu.) - I like Japanese cuisine."
  },
  {
    id: "word052",
    word: "寿司",
    pronunciation: "sushi",
    meaning: "sushi",
    part_of_speech: "noun",
    difficulty: "medium",
    lesson_no: 9,
    when_to_say: "When talking about sushi.",
    example: "寿司を食べに行きましょう。 (sushi wo tabe ni ikimashou.) - Let's go eat sushi."
  },
  {
    id: "word053",
    word: "ラーメン",
    pronunciation: "raamen",
    meaning: "ramen",
    part_of_speech: "noun",
    difficulty: "medium",
    lesson_no: 9,
    when_to_say: "When talking about ramen noodles.",
    example: "昨日ラーメンを食べました。 (kinou raamen wo tabemashita.) - I ate ramen yesterday."
  },
  {
    id: "word054",
    word: "お好み焼き",
    pronunciation: "okonomiyaki",
    meaning: "Japanese savory pancake",
    part_of_speech: "noun",
    difficulty: "difficult",
    lesson_no: 9,
    when_to_say: "When talking about okonomiyaki.",
    example: "大阪のお好み焼きは美味しいです。 (oosaka no okonomiyaki wa oishii desu.) - Osaka's okonomiyaki is delicious."
  },
  {
    id: "word055",
    word: "天ぷら",
    pronunciation: "tempura",
    meaning: "tempura (fried food)",
    part_of_speech: "noun",
    difficulty: "medium",
    lesson_no: 9,
    when_to_say: "When talking about tempura.",
    example: "海老の天ぷらが大好きです。 (ebi no tempura ga daisuki desu.) - I love shrimp tempura."
  },
  {
    id: "word056",
    word: "旅行",
    pronunciation: "ryokou",
    meaning: "travel/trip",
    part_of_speech: "noun",
    difficulty: "difficult",
    lesson_no: 10,
    when_to_say: "When talking about traveling or going on a trip.",
    example: "夏休みに旅行に行きます。 (natsu yasumi ni ryokou ni ikimasu.) - I will go on a trip during summer vacation."
  },
  {
    id: "word057",
    word: "観光",
    pronunciation: "kankou",
    meaning: "sightseeing",
    part_of_speech: "noun",
    difficulty: "difficult",
    lesson_no: 10,
    when_to_say: "When talking about sightseeing or tourism.",
    example: "京都で観光しました。 (kyouto de kankou shimashita.) - I did sightseeing in Kyoto."
  },
  {
    id: "word058",
    word: "ホテル",
    pronunciation: "hoteru",
    meaning: "hotel",
    part_of_speech: "noun",
    difficulty: "medium",
    lesson_no: 10,
    when_to_say: "When talking about a hotel.",
    example: "ホテルを予約しました。 (hoteru wo yoyaku shimashita.) - I made a hotel reservation."
  },
  {
    id: "word059",
    word: "飛行機",
    pronunciation: "hikouki",
    meaning: "airplane",
    part_of_speech: "noun",
    difficulty: "difficult",
    lesson_no: 10,
    when_to_say: "When talking about airplanes.",
    example: "飛行機で日本に行きます。 (hikouki de nihon ni ikimasu.) - I will go to Japan by airplane."
  },
  {
    id: "word060",
    word: "パスポート",
    pronunciation: "pasupooto",
    meaning: "passport",
    part_of_speech: "noun",
    difficulty: "medium",
    lesson_no: 10,
    when_to_say: "When talking about a passport.",
    example: "パスポートを忘れないでください。 (pasupooto wo wasurenaide kudasai.) - Please don't forget your passport."
  }
];

export default japaneseVocabulary; 